# Author: Ninjoh


# Should blood particles be shown on hit?
enableBloodParticleEffect: true

# Should a skull be left behind as a block on the location where a player dies?
enableLeavingBehindPlayerHeadOnDeath: true

# Should blood be left behind on hit (Random chance, the "blood" is redstone wire)?
# WARNING: Players can use this to get infinite redstone supply
enableLeavingBehindBlood: true

# Prevent skulls being placed in mid air? But instead place them
# on the nearest possible block below the player?
preventSkullsBeingPlacedMidAir: true

# The chance (In percentages) to leave "blood" (redstone wire) behind on the ground, on hit
chanceToLeaveBehindBloodOnHit: 50